name: ai_therapist
description: "AI-Powered Addiction Recovery Companion"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  # UI & Design
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  flutter_animate: ^4.5.0
  lottie: ^3.1.2
  shimmer: ^3.0.0
  
  # Firebase
  firebase_core: ^3.3.0
  firebase_auth: ^5.1.4
  cloud_firestore: ^5.2.1
  firebase_storage: ^12.1.3
  firebase_messaging: ^15.0.4
  firebase_analytics: ^11.2.1
  
  # Google Sign In
  google_sign_in: ^6.2.1
  
  # AI & API
  google_generative_ai: ^0.4.3
  dio: ^5.4.3+1
  
  # Supabase for Community Chat
  supabase_flutter: ^2.5.9
  
  # State Management
  provider: ^6.1.2
  flutter_riverpod: ^2.5.1
  
  # Local Storage
  shared_preferences: ^2.2.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.3
  
  # Navigation
  go_router: ^14.2.0
  
  # Utilities
  intl: ^0.19.0
  uuid: ^4.4.0
  connectivity_plus: ^6.0.3
  permission_handler: ^11.3.1
  flutter_local_notifications: ^17.1.2
  
  # Voice & Audio
  speech_to_text: ^6.6.0
  flutter_tts: ^4.0.2
  audioplayers: ^6.0.0
  
  # Charts & Progress
  fl_chart: ^0.68.0
  percent_indicator: ^4.2.3
  
  # Icons & Assets
  flutter_svg: ^2.0.10+1
  cached_network_image: ^3.3.1
  image_picker: ^1.1.2
  
  # Forms & Input
  flutter_form_builder: ^9.3.0
  form_builder_validators: ^10.0.1
  
  # Date & Time
  table_calendar: ^3.1.2
  
  # Animations
  confetti: ^0.7.0
  animated_text_kit: ^4.2.2
  flutter_dotenv: ^5.2.1
dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
