// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlWf69_7Wmneg30o7e3eEJEDQf3ZZpC5M',
    appId: '1:840648616109:web:7141e0ba448395f545be24',
    messagingSenderId: '840648616109',
    projectId: 'ai-therapist-app-c5464',
    authDomain: 'ai-therapist-app-c5464.firebaseapp.com',
    storageBucket: 'ai-therapist-app-c5464.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBh48C9BIHGFa8iFHFjqQSvUV0bT6bhT84',
    appId: '1:840648616109:android:ee6215a27a9f555a45be24',
    messagingSenderId: '840648616109',
    projectId: 'ai-therapist-app-c5464',
    storageBucket: 'ai-therapist-app-c5464.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBlWf69_7Wmneg30o7e3eEJEDQf3ZZpC5M',
    appId: '1:840648616109:web:0b987a9050092dea45be24',
    messagingSenderId: '840648616109',
    projectId: 'ai-therapist-app-c5464',
    authDomain: 'ai-therapist-app-c5464.firebaseapp.com',
    storageBucket: 'ai-therapist-app-c5464.firebasestorage.app',
  );

}